### ISSUE TITLE
Add a table for notifications

### ISSUE THREAD

**Issue by edaloicaro18** [themaxsandelin/twitter#1]
Your table schema is the most complete that I have been able to find, but I can't see anything related to notification? What changes do you think would be necessary so that this db would also support notifications , for example, whenever a a tweet is favorited or a user gets a new follower?

Thanks.

**Comment by themaxsandelin** [comment]
Hey man,

Thanks for taking an interest in my old Twitter app, built this thing so long ago. I don't think there is much to be added but a very simple table to keep track of the notification "connections". Since notification texts and formats can change, it's important to find a basic structure for them with types of notifications and more, then have the output in the actual application code.

Then you'd probably want to set up WebSockets on the backend and frontend to push notifications to the user within the app. Sure you can use service workers, but we don't want browser notifications but rather in-app notifications.

Feel free to contribute anything you want through your own branch, as I don't have the time right now to work on this. 👍

**Comment by Ziovice** [comment]
2019?

**Comment by themaxsandelin** [comment]
Closing this now. :)
